config/routes.rb
  get 'nutritie4/export_to_xlsx', to: 'nutritie4#export_to_xlsx_plata_nutritie4', as: 'export_nutritie4_xlsx'
  
  get 'nutritie5', to: 'nutritie5#index'
  get 'nutritie5/export_to_xlsx', to: 'nutritie5#export_to_xlsx_plata_nutritie5', as: 'export_nutritie5_xlsx'
  get 'contract/contract_voluntar', to: 'contractes#semneaza_contract', as: 'contract_voluntar'
  get 'contract/contract_voluntar1', to: 'contractes#semneaza_contract1', as: 'contract_voluntar1'

  post '/contractes', to: 'contractes#create', as: 'contractes_create' # Aici, 'contractes_create' este numele rutei
  #get 'contractes/vizualizeaza/:id', to: 'contractes#vizualizeaza_contract', as: 'contracte_vizualizeaza'
  get 'contractes/:id/vizualizeaza', to: 'contractes#vizualizeaza_contract', as: 'vizualizeaza_contract_contracte'
  get 'contractes/all', to: 'contractes#contracte_all', as: 'contracte_all'
  get 'contracte_useri/:id/show_pdf', to: 'contractes#show_pdf', as: 'contract_pdf'
  get 'contractes/preluare_emailuri', to: 'contractes#preluare_emailuri_din_text'

 
  get 'vizualizeaza_contract', to: 'contractes#vizualizeaza_contract', as: 'contractes_vizualizeaza_contract'
  get '/voluntariat', to: 'contractes#voluntariat', as: 'voluntariat'
  get '/voluntar', to: 'contractes#voluntar', as: 'voluntar' 
  get '/cerere_voluntar', to: 'contractes#cerere_voluntar', as: 'cerere_voluntar'
  
  get '/cerere_voluntar1', to: 'contractes#cerere_voluntar1', as: 'cerere_voluntar1'
  get '/gdpr', to: 'contractes#gdpr', as: 'gdpr' #pentru voluntari
  get '/gdpr1', to: 'contractes#gdpr1', as: 'gdpr1' #pentru contractori

  get '/ssm', to: 'contractes#ssm', as: 'ssm' #pentru voluntari
  get '/isu', to: 'contractes#isu', as: 'isu' #pentru voluntari

  get '/fisa_postului', to: 'contractes#fisa_postului', as: 'fisa_postului'
  get '/fisa_postului1', to: 'contractes#fisa_postului1', as: 'fisa_postului1'

  delete 'contractes/:id/destroy_contracte_useri', to: 'contractes#destroy_contracte_useri', as: 'destroy_contracte_useri'
  post 'verifica_cod', to: 'contractes#verifica_cod'
  
  resources :contractes do
    member do
      get 'view_contracte_useri', to: 'contractes#view_contracte_useri'
      get 'edit_contracte_useri', to: 'contractes#edit_contracte_useri'
      post :create_or_update_contracte_useri
      match 'create_or_update_contracte_useri', to: 'contractes#create_or_update_contracte_useri', via: [:post, :patch]
      post 'salveaza_gdpr', to: 'contractes#salveaza_gdpr'
      post 'salveaza_ssm', to: 'contractes#salveaza_ssm'
      post 'salveaza_isu', to: 'contractes#salveaza_isu'
      post 'salveaza_contract', to: 'contractes#salveaza_contract'
      post 'salveaza_fisa_postului', to: 'contractes#salveaza_fisa_postului'

    end
  end
  

  resources :tipconstitutionals
  get 'evaluare_tipologie_ayurvedica', to: 'tipconstitutionals#evaluare_tipologie_ayurvedica'
  get 'calculate_totals', to: 'tipconstitutionals#process_totals'
  
  get 'test1', to: 'tipconstitutionals#test1'
  
  resources :modulecursuris
  get '/crypto_prices/show_crypto_price', to: 'crypto_prices#show_crypto_price', as: 'show_crypto_price'

  get 'tayt12/index'
  
  get 'tayt12/transport_international/:return_to', to: 'tayt12#transport_international', as: :tayt12_transport_international
  get 'video/link/:return_to', to: 'videos#linkocazional', as: 'video_link', defaults: { return_to: 'default' }



  get '/an2', to: 'cursuriayurvedas#cursayurveda'
  get '/cursayurveda2425', to: 'cursuriayurvedas#cursayurveda2425'
  
  get '/an3', to: 'cursuriayurvedas#an2'
  get '/an4', to: 'cursuriayurvedas#an3'
  get '/an', to: 'cursuriayurvedas#an'

  resources :cursuriayurvedas
  get 'nutritie1', to: 'nutritie1#index'
  get 'nutritie', to: 'nutritie1#nutritie'
  get 'nutritie2', to: 'nutritie2#index'
  get 'nutritie3', to: 'nutritie3#index'
  get 'nutritie4', to: 'nutritie4#index'
  get 'myvideo', to: 'videos#myvideo'
  get 'videos/:id/myvideo1', to: 'videos#myvideo1', as: 'myvideo1'
  get 'videos/:id/myvideo2', to: 'videos#myvideo2', as: 'myvideo2'
  get 'videos/:id/myvideo3', to: 'videos#myvideo3', as: 'myvideo3' 
  get 'videos/:id/myvideo4', to: 'videos#myvideo4', as: 'myvideo4' 
  get 'videos/:id/myvideo44', to: 'videos#myvideo44', as: 'myvideo44'
  get 'videos/:id/myvideo444', to: 'videos#myvideo444', as: 'myvideo444'
  get 'videos/:id/myvideo6', to: 'videos#myvideo6', as: 'myvideo6' 
  get 'videos/:id/myvideo67', to: 'videos#myvideo67', as: 'myvideo67'
  get 'videos/:id/myvideo7', to: 'videos#myvideo7', as: 'myvideo7'
  get 'videos/:id/myvideo8', to: 'videos#myvideo8', as: 'myvideo8'
  get 'videos/:id/myvideo9', to: 'videos#myvideo9', as: 'myvideo9'
  get 'videos/:id/myvideo10', to: 'videos#myvideo10', as: 'myvideo10'
  get 'videos/:id/myvideo11', to: 'videos#myvideo11', as: 'myvideo11'
  get 'videos/:id/myvideo12', to: 'videos#myvideo12', as: 'myvideo12'
  get 'videos/:id/myvideo122', to: 'videos#myvideo122', as: 'myvideo122'
  get 'videos/:id/myvideo13', to: 'videos#myvideo13', as: 'myvideo13'
  get 'videos/:id/myvideo133', to: 'videos#myvideo133', as: 'myvideo133'
  get 'videos/:id/myvideo14', to: 'videos#myvideo14', as: 'myvideo14'
  get 'videos/:id/myvideo144', to: 'videos#myvideo144', as: 'myvideo144'
  get 'videos/:id/myvideo15', to: 'videos#myvideo15', as: 'myvideo15'
  get 'videos/:id/myvideo16', to: 'videos#myvideo16', as: 'myvideo16'
  get 'videos/:id/myvideo17', to: 'videos#myvideo17', as: 'myvideo17'
  get 'videos/:id/myvideo18', to: 'videos#myvideo18', as: 'myvideo18'
  get 'videos/:id/myvideo19', to: 'videos#myvideo19', as: 'myvideo19'
  get 'videos/:id/myvideo20', to: 'videos#myvideo20', as: 'myvideo20'
  get 'videos/:id/myvideo21', to: 'videos#myvideo21', as: 'myvideo21'
  get 'videos/:id/myvideo22', to: 'videos#myvideo22', as: 'myvideo22'
  get 'videos/:id/myvideo23', to: 'videos#myvideo23', as: 'myvideo23'
  get 'videos/:id/myvideo24', to: 'videos#myvideo24', as: 'myvideo24'
  get 'videos/:id/myvideo25', to: 'videos#myvideo25', as: 'myvideo25'
  get 'videos/:id/myvideo26', to: 'videos#myvideo26', as: 'myvideo26'
  get 'videos/:id/myvideo27', to: 'videos#myvideo27', as: 'myvideo27'
  get 'videos/:id/myvideo28', to: 'videos#myvideo28', as: 'myvideo28'
  get 'videos/tayv2', to: 'videos#tayv2', as: 'tayv2'
  get 'tabara_de_ayurveda_toamna1', to: 'videos#tayt12', as: 'tayt12'
  get 'tabara_de_ayurveda_toamna2', to: 'videos#tayt122', as: 'tayt122'

  
  resources :videos
  get 'facturas/facturi_xml', to: 'facturas#facturi_xml', as: 'facturi_xml'#pt xml
  get 'facturas/:id/download_xml', to: 'facturas#download_xml', as: 'download_xml_factura' #pt xml
  get 'facturas/:id/download_xml_company', to: 'facturas#download_xml_company', as: 'download_xml_company_factura'
  get 'facturas/:id/download_xml_individual', to: 'facturas#download_xml_individual', as: 'download_xml_individual_factura'

  get 'facturas/download_zip', to: 'facturas#download_all_xml', as: 'facturas_download_zip'
  


  get 'facturas/facturi_xml_ayushcell', to: 'facturas#facturi_xml_ayushcell', as: 'facturi_xml_ayushcell'#pt xml
  # Root route
  get 'facturas/generate_pdf', to: 'facturas#generate_pdf', as: 'generate_pdf_facturas'
  #get 'facturas/download_all', to: 'facturas#download_all', defaults: { format: 'pdf' } 
  #get 'facturas/download_all', to: 'facturas#download_all', as: 'download_all_facturas'
  get 'facturas/download_all', to: 'facturas#download_all', as: 'download_all_facturas', defaults: { format: 'pdf' } 
  get 'facturas/download_all_xml', to: 'facturas#download_all_xml', as: 'download_all_facturas_xml', defaults: { format: 'xml' }
 
  get 'facturas/download1', to: 'facturas#download1', as: 'download1_factura'
  get 'facturas/:id/download', to: 'facturas#download', as: 'download_factura'
  get 'facturicomenzi', to: 'facturas#facturicomenzi'
  get 'facturas/:id', to: 'facturas#show', format: 'pdf'
  


  resources :facturas, path: 'factura', except: :index
  get 'factura', to: 'facturas#index'
  
  


# config/routes.rb
post '/stripe_webhooks', to: 'stripe_webhooks_controller#payment_success' #ruta pt trimis notificare (email) cand am factura noua
post '/stripe-webhooks', to: 'stripe_webhooks#create'


 get '/detaliifacturares/:id/pay', to: 'detaliifacturares#pay', as: 'detaliifacturare_pay'
 get 'detaliifacturares/:id/get_stripe_session_id', to: 'detaliifacturares#get_stripe_session_id', as: 'get_stripe_session_id'
 patch 'detaliifacturares/:id/update1', to: 'detaliifacturares#update1', as: 'detaliifacturare_update1'
 get 'detaliifacturares/:id/edit1', to: 'detaliifacturares#edit1', as: 'detaliifacturare_edit1'

  get 'prods/produscurent'
  

  get 'edit_comenziprod/:comanda_id', to: 'comandas#edit_comenziprod', as: :edit_comenziprod
  patch 'comandas/:id/update_comenziprod', to: 'comandas#update_comenziprod', as: :update_comenziprod
  get 'select_comanda_id', to: 'comandas#select_comanda_id'
  post 'select_edit_comenziprod', to: 'comandas#select_edit_comenziprod'

  resources :prods
  get 'comandas/index11', to: 'comandas#index11', as: :index11_comandas
  get 'comandas/new11', to: 'comandas#new11', as: :new11_comandas
  post 'comandas/create11', to: 'comandas#create11', as: :create11_comandas

  # Configurația unificată pentru resources :comandas
  resources :comandas do
    collection do
      # Poti adauga aici alte rute de tip collection dacă este necesar
    end
    member do
      
      patch 'update11', to: 'comandas#update11'
      get 'edit11', to: 'comandas#edit11', as: :edit11_comanda
      
      delete 'destroy11', to: 'comandas#destroy11', as: :destroy11_comanda
    end
  end
  
 
  
  #post 'detaliifacturares/create'
  mount Ahoy::Engine => "/ahoy"
  resources :lista_vegetales
  resources :paginisites
  get 'userilogati', to: 'paginisites#userilogati'
  get '/useriunici_logati', to: 'paginisites#useriunici_logati', as: 'useriunici_logati_paginisites'
  get '/useriunici_logati/export', to: 'paginisites#export_to_xlsx', as: 'export_useriunici_logati'

app/models/cursuriayurveda.rb
class Cursuriayurveda < ApplicationRecord
end

app/helpers/cursuriayurvedas_helper.rb
module CursuriayurvedasHelper
end

app/views/cursuriayurvedas/_cursuriayurveda.html.erb
<div id="<%= dom_id cursuriayurveda %>">
  <p>
    <strong>Grupa:</strong>
    <%= cursuriayurveda.grupa %>
  </p>

</div>

app/views/cursuriayurvedas/_form.html.erb
<%= form_with(model: cursuriayurveda) do |form| %>
  <% if cursuriayurveda.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cursuriayurveda.errors.count, "error") %> prohibited this cursuriayurveda from being saved:</h2>

      <ul>
        <% cursuriayurveda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :grupa, style: "display: block" %>
    <%= form.text_field :grupa %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cursuriayurvedas/_video.html.erb
<tr>
  <td><%= video.nume %></td>
  <td><%= video.descriere %></td>
  <td><%= video.sursa %></td>
  <td><%= video.link %></td>
  <td><%= video.tip %></td>
  <td><%= video.ordine %></td>
  <td><%= video.luna %></td>
  <td><%= video.cod %></td>
  <td>
   
    <%= link_to "Edit", edit_video_path(video), class: "btn btn-warning" %>
    <%= link_to "Delete", video, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    <%= link_to "Vezi video", myvideo1_path(id: video.id, link: video.link), class: "btn btn-primary" %>



  </td>
  
</tr>

app/views/cursuriayurvedas/_video1.html.erb
<tr>
<% if video.tip == 'an1' %>
<td>
  <% if video.ordine > 1000 %>
    <%= video.ordine - 1000 %>
  <% else %>
    <%= video.ordine %>
  <% end %>
</td>
<% end %>

<% if video.tip == 'an2' %>
<td>
<%= video.ordine %>
</td>
<% end %>

<% if video.tip == 'an3' %>
<td>
<%= video.ordine %>
</td>
<% end %>
  <td><%= video.nume %></td>
  <td><%= video.descriere %></td>
 
  <td>
   
   
    <%= link_to "Vezi video", myvideo3_path(id: video.id, link: video.link), class: "btn btn-primary" %>



  </td>
  
</tr>

app/views/cursuriayurvedas/an.html.erb
<% content_for :title, "Cursuri de Ayurveda I Aplicații Plante I Vizionări Tabere și Seminarii" %>
<% content_for :description, "Ayush Cell Romania: Cursuri de Ayurveda, Nutriție, Aplicații Plante Medicinale și Resurse Vegetale" %>
<% content_for :keywords, "cursuri de ayurveda, cursuri de nutritie, plante medicinale, alimentație sănătoasă, calculator nutrițional, dieta, tabere de ayurveda," %>
<% content_for :canonical do %>
  <link rel="canonical" href="https://www.ayushcell.ro">
<% end %>

<div class="container" id="first-page">
  <%= render 'layouts/sideleft' %>

  <div class="cr" style="background-color: aliceblue;">
    <h1 class="first-tittle">Ayush Cell Romania: Cursuri, Aplicații, Tabere, Vizionări</h1>
    <h2 class="main-title">Anul de studiu 2023 - 2024</h2>
    <h2 class="cr-title" style="margin-top: 10px;">Ayush Cell Romania</h2>

    <% emailuri_permise = ['karunasland@hotmail.com','v_ionela@yahoo.com','amordeshakti@yahoo.es']%>

    <% if current_user && (current_user.role == 1 || emailuri_permise.include?(current_user.email)) %>
      <h2 style= "text-align: center;padding: 0 10px;">Contributie Curs Ayurveda</h2>
      <br>

      <%= form_with url: datefacturarep_path(s: @prod.id), method: :post, local: true, data: { turbo: false } do |form| %>
      
        
        <%= form.hidden_field :s, value: @prod.id %>
        
        <div class="table-responsive" style="margin-right: auto; margin-left: 0;">
          <table class="table table-striped table-bordered table-hover">
            <thead class="thead-dark">
              <tr class="desk">
                <th>Servicii</th>
                <th>Detalii</th>
                <th>Detalii plata</th>
                <th>Cantitate</th>              
                <th>Pret bucata</th>                
                <th>Pret total</th>
                <th>Actiune</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td> <%= @prod.nume %> </td>
                <td><%= @prod.detalii %></td>
                <td>
                    <%= form.text_field :obs, value: @obs, placeholder: 'Ex: plata ianuarie', required: true %>
                </td>

                <td style="text-align:center;">
                  <%= form.select :cantitate, options_for_select((1..11).map { |numar| numar }), {}, { class: 'form-control', id: 'cantitateSelect' } %>
                </td>
                <td id="pretBucata" style="text-align:center;"><%= @prod.pret.to_f.to_i %> lei</td>
                <td id="pretTotal" style="text-align:center;">---</td>
                <td style="text-align:center;">
                  <%= form.submit "Comanda", id: 'buttonComanda', class: 'btn btn-primary' %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<script>
document.addEventListener("turbo:load", function() {
  console.log("Turbo load triggered");
  initComandaForm();
});

function initComandaForm() {
  updatePret();

  document.getElementById('cantitateSelect').addEventListener('change', function() {
    updatePret();
  });
}

function calculeazaPret(n) {
  var pretPeBucata = parseFloat(document.getElementById('pretBucata').textContent.replace(' lei', ''));
  return pretPeBucata * n;
}

function updatePret() {
  var cantitate = parseInt(document.getElementById('cantitateSelect').value, 10);
  var pretTotal = calculeazaPret(cantitate);

  document.getElementById('pretTotal').textContent = pretTotal.toFixed(0) + ' lei';
}
</script>

app/views/cursuriayurvedas/an2.html.erb
<% content_for :title, "Cursuri de Ayurveda I Aplicații Plante I Vizionări Tabere și Seminarii" %>
<% content_for :description, "Ayush Cell Romania: Cursuri de Ayurveda, Nutriție, Aplicații Plante Medicinale și Resurse Vegetale" %>
<% content_for :keywords, "cursuri de ayurveda, cursuri de nutritie, plante medicinale, alimentație sănătoasă, calculator nutrițional, dieta, tabere de ayurveda," %>
<% content_for :canonical do %>
  <link rel="canonical" href="https://www.ayushcell.ro">
<% end %>
<div class="container" id="first-page">
<%= render 'layouts/sideleft' %>

<div class="cr" style="background-color: aliceblue;">
    <h1 class="first-tittle">Ayush Cell Romania: Cursuri, Aplicații, Tabere, Vizionări</h1>



    <h2 class="cr-title" style="margin-top: 10px;">Ayush Cell Romania</h2>
    <h2 class="main-title" >Grupa 03 - anul de studiu 2024 - 2025</h2>
    <%if current_user &&  @prods_an3_2425.count>0%>
 <div class="tbland">
 <h2 style= "text-align: center;padding: 0 10px;">Accesare cursuri Ayurveda</h2></br>
 
 <div class="tbr">
   <table class="table table-striped table-hover">
       <thead>
           <tr>
               <th style="width: auto;">Curs de Ayurveda</th>
               <th style="width: auto;">Detalii</th>
               
               <th style="width: auto;">Pret</th>
               <th style="width: auto;">Selecție</th>
           </tr>
       </thead>
       <tbody>
       
       <%  @prods_an3_2425.each do |prod| %>
           <tr>
               <td> <%= prod.nume %> </td>                        
               <td><%= prod.detalii %></td> 
               
               <td><%= prod.pret.to_i %> lei</td>
               <td> <%= link_to 'Comanda', datefacturare_path(s: prod.id), class: 'btn no-turbo' %> </td>      
           </tr>  
       <% end %>
       
       </tbody>
     </table>
   </div></div>
   <% end %>




<br><br>

<% if current_user && (current_user.role == 1 || @video_an3_2425.count > 0) %>
<h2 style= "text-align: center;padding: 0 10px;">Înregistrări video Grupa 3 </h2></br>
  
  
<div id="videos">
<table class="table">
  <thead>
  <tr>
      <th>Nr</th>
      <th>Nume</th>
      <th>Descriere</th>       
      <th>Actiune</th>
      
  </tr>
  </thead>
  <tbody>
  <% @video_an3_2425.each do |video| %>
      <tr>
      <td><%= video.ordine %></td>
      <td><%= video.nume %></td>
      <td><%= video.descriere %></td>           
      <td><%= link_to "Vezi video", myvideo17_path(id: video.id, link: video.link), class: "btn btn-primary" %></td>
      </tr>

    <% end %>
  </tbody>
</table>
</div>
    
    
    
    <% end %>

<br><br><br><br><br>




    <h2 class="main-title" >Grupa 02 - anul de studiu 2023 - 2024</h2>

   <h2 class="cr-title" style="margin-top: 10px;">Ayush Cell Romania</h2>

<% if current_user && @prods.count > 0 %>
<div class="tbland">
    <h2 style="text-align: center; padding: 0 10px;">Accesare cursuri Ayurveda</h2><br>

    <div class="selector">
        <label for="course-selector-1" style="padding:5px;">Alege cursul: </label>
        <select id="course-selector-1" style="padding:5px;">
            <% @prods.each_with_index do |prod, index| %>
                <option value="<%= index %>"><%= prod.nume %></option>
            <% end %>
        </select>
    </div>

    <div class="tbr">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th style="width: auto;">Curs de Ayurveda</th>
                    <th style="width: auto;">Detalii</th>
                    <th style="width: auto;">Pret</th>
                    <th style="width: auto;">Selecție</th>
                </tr>
            </thead>
            <tbody>
                <% @prods.each_with_index do |prod, index| %>
                    <tr class="ayurveda-row" style="display: none;">
                        <td><%= prod.nume %></td>
                        <td><%= prod.detalii %></td>
                        <td><%= prod.pret.to_i %> lei</td>
                        <td><%= link_to 'Comanda', datefacturare_path(s: prod.id), class: 'btn no-turbo' %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>
<% end %>

<% if current_user && @platit %>
<h2 style="text-align: center; padding: 0 10px;">Înregistrări video Grupa 2</h2><br>

<div class="selector">
    <label for="course-selector-2" style="padding:5px;">Vezi video: </label>
    <select id="course-selector-2" style="padding:5px;">
        <% @myvideo.each_with_index do |video, index| %>
            <option value="<%= index %>"><%= video.nume %></option>
        <% end %>
    </select>
</div>

<div id="videos">
    <table class="table">
        <thead>
            <tr>
                <th>Nr</th>
                <th>Nume</th>
                <th>Descriere</th>
                <th>Actiune</th>
            </tr>
        </thead>
        <tbody id="video-tbody">
            <% @myvideo.each_with_index do |video, index| %>
                <tr class="new-row" style="display: none;">
                    <td><%= index + 1 %></td>
                    <td><%= video.nume %></td>
                    <td><%= video.descriere %></td>
                    <td style="text-align:center;">
                        <%= link_to "Vezi video", myvideo3_path(id: video.id, link: video.link), class: "btn btn-primary" %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<% end %>
</div></div>
<script>
document.addEventListener("turbo:load", function() {
    function setupSelector(selectorId, rowClass) {
        const selector = document.getElementById(selectorId);
        const rows = document.querySelectorAll('.' + rowClass);

        function showSelectedRow() {
            const selectedIndex = parseInt(selector.value, 10);
            rows.forEach((row, index) => {
                row.style.display = index === selectedIndex ? 'table-row' : 'none';
            });
        }

        selector.addEventListener('change', showSelectedRow);

        // Initial display setup
        showSelectedRow();
    }

    // Setup selectors for both tables
    setupSelector('course-selector-1', 'ayurveda-row');
    setupSelector('course-selector-2', 'new-row');
});
</script>

app/views/cursuriayurvedas/edit.html.erb
<h1>Editing cursuriayurveda</h1>

<%= render "form", cursuriayurveda: @cursuriayurveda %>

<br>

<div>
  <%= link_to "Show this cursuriayurveda", @cursuriayurveda %> |
  <%= link_to "Back to cursuriayurvedas", cursuriayurvedas_path %>
</div>

app/views/cursuriayurvedas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cursuriayurvedas</h1>

<div id="cursuriayurvedas">
  <% @cursuriayurvedas.each do |cursuriayurveda| %>
    <%= render cursuriayurveda %>
    <p>
      <%= link_to "Show this cursuriayurveda", cursuriayurveda %>
    </p>
  <% end %>
</div>

<%= link_to "New cursuriayurveda", new_cursuriayurveda_path %>

app/views/cursuriayurvedas/myvideo1.html.erb
<!-- Partea de sus a fișierului app/views/home/about.html.erb -->
<% content_for :custom_js do %>
    <%= raw File.read(Rails.root.join('app', 'javascript', 'epytv.js')) %>
    <% end %>
<section class="c1"></br>
<h1 style= "text-align: center;padding: 0 10px;"><%=@myvideo1.nume%></h1></br>
<!-- for non autoplay video //-->
<div style="width: 80%; max-width: 640px; max-height: 360px; margin: 0 auto; background-image: url(<%= asset_path 'player.png' %>);background-size: 100%;">
    <div class="epyv-video-container" id="epyv-container[<%= @myvideo %>]">
        <div id="epytvPlayButton[<%= @myvideo %>]" class="play-button" onClick="clickToPlay('<%= @myvideo %>');"></div>
        <img id="epytvImage[<%= @myvideo %>]" src="/thumbnails/video-thumbnail-filename" />
        <div class="epyv-video-player" id="<%= @myvideo %>" data-params="controls=1,rel=1,autoplay=0"></div>
        <div id="epytvPlayerCounter[<%= @myvideo %>]" class="playerCounter" style="visibility: hidden;">10</div>
    </div>
</div></br></br></br>
</section>
<script>
  document.addEventListener("turbo:load", function() {
    document.querySelectorAll('.no-turbo').forEach(link => {
      link.setAttribute('data-turbo', 'false');
    });
  });
</script>
<script>
<%= yield :custom_js %>
</script>

app/views/cursuriayurvedas/new.html.erb
<h1>New cursuriayurveda</h1>

<%= render "form", cursuriayurveda: @cursuriayurveda %>

<br>

<div>
  <%= link_to "Back to cursuriayurvedas", cursuriayurvedas_path %>
</div>

app/views/cursuriayurvedas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cursuriayurveda %>

<div>
  <%= link_to "Edit this cursuriayurveda", edit_cursuriayurveda_path(@cursuriayurveda) %> |
  <%= link_to "Back to cursuriayurvedas", cursuriayurvedas_path %>

  <%= button_to "Destroy this cursuriayurveda", @cursuriayurveda, method: :delete %>
</div>