config/routes.rb
  get 'videos/:id/myvideo16', to: 'videos#myvideo16', as: 'myvideo16'
  get 'videos/:id/myvideo17', to: 'videos#myvideo17', as: 'myvideo17'
  get 'videos/:id/myvideo18', to: 'videos#myvideo18', as: 'myvideo18'
  get 'videos/:id/myvideo19', to: 'videos#myvideo19', as: 'myvideo19'
  get 'videos/:id/myvideo20', to: 'videos#myvideo20', as: 'myvideo20'
  get 'videos/:id/myvideo21', to: 'videos#myvideo21', as: 'myvideo21'
  get 'videos/:id/myvideo22', to: 'videos#myvideo22', as: 'myvideo22'
  get 'videos/:id/myvideo23', to: 'videos#myvideo23', as: 'myvideo23'
  get 'videos/:id/myvideo24', to: 'videos#myvideo24', as: 'myvideo24'
  get 'videos/:id/myvideo25', to: 'videos#myvideo25', as: 'myvideo25'
  get 'videos/:id/myvideo26', to: 'videos#myvideo26', as: 'myvideo26'
  get 'videos/:id/myvideo27', to: 'videos#myvideo27', as: 'myvideo27'
  get 'videos/:id/myvideo28', to: 'videos#myvideo28', as: 'myvideo28'
  get 'videos/tayv2', to: 'videos#tayv2', as: 'tayv2'
  get 'tabara_de_ayurveda_toamna1', to: 'videos#tayt12', as: 'tayt12'
  get 'tabara_de_ayurveda_toamna2', to: 'videos#tayt122', as: 'tayt122'

  
  resources :videos
  get 'facturas/facturi_xml', to: 'facturas#facturi_xml', as: 'facturi_xml'#pt xml
  get 'facturas/:id/download_xml', to: 'facturas#download_xml', as: 'download_xml_factura' #pt xml
  get 'facturas/:id/download_xml_company', to: 'facturas#download_xml_company', as: 'download_xml_company_factura'
  get 'facturas/:id/download_xml_individual', to: 'facturas#download_xml_individual', as: 'download_xml_individual_factura'

  get 'facturas/download_zip', to: 'facturas#download_all_xml', as: 'facturas_download_zip'
  


  get 'facturas/facturi_xml_ayushcell', to: 'facturas#facturi_xml_ayushcell', as: 'facturi_xml_ayushcell'#pt xml
  # Root route
  get 'facturas/generate_pdf', to: 'facturas#generate_pdf', as: 'generate_pdf_facturas'
  #get 'facturas/download_all', to: 'facturas#download_all', defaults: { format: 'pdf' } 
  #get 'facturas/download_all', to: 'facturas#download_all', as: 'download_all_facturas'
  get 'facturas/download_all', to: 'facturas#download_all', as: 'download_all_facturas', defaults: { format: 'pdf' } 
  get 'facturas/download_all_xml', to: 'facturas#download_all_xml', as: 'download_all_facturas_xml', defaults: { format: 'xml' }
 
  get 'facturas/download1', to: 'facturas#download1', as: 'download1_factura'
  get 'facturas/:id/download', to: 'facturas#download', as: 'download_factura'
  get 'facturicomenzi', to: 'facturas#facturicomenzi'
  get 'facturas/:id', to: 'facturas#show', format: 'pdf'
  


  resources :facturas, path: 'factura', except: :index
  get 'factura', to: 'facturas#index'
  
  


# config/routes.rb
post '/stripe_webhooks', to: 'stripe_webhooks_controller#payment_success' #ruta pt trimis notificare (email) cand am factura noua
post '/stripe-webhooks', to: 'stripe_webhooks#create'


 get '/detaliifacturares/:id/pay', to: 'detaliifacturares#pay', as: 'detaliifacturare_pay'
 get 'detaliifacturares/:id/get_stripe_session_id', to: 'detaliifacturares#get_stripe_session_id', as: 'get_stripe_session_id'
 patch 'detaliifacturares/:id/update1', to: 'detaliifacturares#update1', as: 'detaliifacturare_update1'
 get 'detaliifacturares/:id/edit1', to: 'detaliifacturares#edit1', as: 'detaliifacturare_edit1'

  get 'prods/produscurent'
  

  get 'edit_comenziprod/:comanda_id', to: 'comandas#edit_comenziprod', as: :edit_comenziprod
  patch 'comandas/:id/update_comenziprod', to: 'comandas#update_comenziprod', as: :update_comenziprod
  get 'select_comanda_id', to: 'comandas#select_comanda_id'
  post 'select_edit_comenziprod', to: 'comandas#select_edit_comenziprod'

  resources :prods
  get 'comandas/index11', to: 'comandas#index11', as: :index11_comandas
  get 'comandas/new11', to: 'comandas#new11', as: :new11_comandas
  post 'comandas/create11', to: 'comandas#create11', as: :create11_comandas

  # Configurația unificată pentru resources :comandas
  resources :comandas do
    collection do
      # Poti adauga aici alte rute de tip collection dacă este necesar
    end
    member do
      
      patch 'update11', to: 'comandas#update11'
      get 'edit11', to: 'comandas#edit11', as: :edit11_comanda
      
      delete 'destroy11', to: 'comandas#destroy11', as: :destroy11_comanda
    end
  end
  
 
  
  #post 'detaliifacturares/create'
  mount Ahoy::Engine => "/ahoy"
  resources :lista_vegetales
  resources :paginisites
  get 'userilogati', to: 'paginisites#userilogati'
  get '/useriunici_logati', to: 'paginisites#useriunici_logati', as: 'useriunici_logati_paginisites'
  get '/useriunici_logati/export', to: 'paginisites#export_to_xlsx', as: 'export_useriunici_logati'
  get '/useriunici_nelogati/export', to: 'paginisites#export_to_xlsx_no_login', as: 'export_useriunici_nelogati'
  get '/plata_nutritie3/export', to: 'paginisites#export_to_xlsx_plata_nutritie3', as: 'export_plata_nutritie3'
  get '/plata_amnaya/export', to: 'paginisites#export_to_xlsx_plata_amnaya', as: 'export_plata_amnaya'
  get '/plata_vajikarana_modul1/export', to: 'paginisites#export_to_xlsx_plata_vajikarana_modul1', as: 'export_to_xlsx_plata_vajikarana_modul1'
  get '/plata_vajikarana_modul2/export', to: 'paginisites#export_to_xlsx_plata_vajikarana_modul2', as: 'export_to_xlsx_plata_vajikarana_modul2'
  
  get '/export_to_xlsx_plata_psihofonoterapie/export', to: 'paginisites#export_to_xlsx_plata_psihofonoterapie', as: 'export_to_xlsx_plata_psihofonoterapie'
  
  get '/plata_tayv2/export', to: 'paginisites#export_to_xlsx_plata_tayv2', as: 'export_plata_tayv2'
  get '/plata_tayt12/export', to: 'paginisites#export_to_xlsx_plata_tayt12', as: 'export_plata_tayt12'
  get '/export_to_xlsx_plata_sesiunevara/export', to: 'paginisites#export_to_xlsx_plata_sesiunevara', as: 'export_to_xlsx_plata_sesiunevara'
  
  get 'export_plata_rasayana_modul1', to: 'paginisites#export_to_xlsx_plata_rasayana_modul1'

  
  get '/plata_an1/export', to: 'paginisites#export_to_xlsx_plata_an1', as: 'export_plata_an1'
  get '/plata_an1/summary_export', to: 'paginisites#export_to_xlsx_summary', as: 'export_to_xlsx_summary'
  get '/plata_an1/summary_export_2024_2025', to: 'paginisites#export_to_xlsx_summary_2024_2025', as: 'export_to_xlsx_summary_2024_2025'


  get '/plata_an1_2024_2025/export', to: 'paginisites#export_to_xlsx_plata_an1_2024_2025', as: 'export_plata_an1_2024_2025'


  get '/paginisites/:id/statistici_utilizator', to: 'paginisites#statistici_utilizator', as: 'statistici_utilizator_paginisite'
  get 'export_plata_an2_2425', to: 'paginisites#export_to_xlsx_plata_an2_2425' #an 2 2425 dupa comanda_id
  get 'export_to_xlsx_plata_generala_curs1', to: 'paginisites#export_to_xlsx_plata_generala_curs1'
  
  
  resources :statistics, only: [:index]
  
  get 'authentication/login'
  get 'admin/index'
  put 'admin/update/:id', to: 'admin#update', as: 'update_admin'
  get 'admin/edit/:id', to: 'admin#edit', as: 'edit_admin'
  get 'admin/new', to: 'admin#new', as: 'new_admin'
  
  
 # în routes.rb
 
  get 'detaliifacturare', to: 'detaliifacturares#datefacturare', as: 'datefacturare'  
 
  post 'datefacturarep', to: 'detaliifacturares#datefacturarep'
  



  resources :detaliifacturares, only: [:index, :edit, :create, :update, :datefacturare, :show]
  
  
  


  post 'admin/create', to: 'admin#create', as: 'create_admin'
  

  
  
  get '/aplicatie-calcul-nutritional', to: 'valorinutritionales#aplicatie', as: :aplicatie


  resources :valorinutritionales, only: [:index], path: 'valori-nutritionale' do
    collection do
      post :calculate
      post :select_valorinutritionales, path: 'select'
      post :reset_session_data, path: 'reset_session_data'
      post :delete_selected
      get :show_selected
      get :valorinutritionales_table
      get :index_turbo_stream
      post :selected_records
      get :pagination_turbo_stream
      post :process_selected
      post :track
    end
  end
  
  get 'sesiune_vara', to: 'home#sesiune_vara'
  get 'home/recuperare_cursuri', to: 'home#recuperare_cursuri'
  get 'home/index1', to: 'home#index1'
  get 'home/index'
  get 'vajikarana', to: 'home#vajikarana'
  
  get 'newsletter', to: 'home#newsletter'
  
  get 'sesiune_vara_raport', to: 'home#sesiune_vara_raport'
  get 'copyright', to: 'home#copyright'
  get 'documente', to: 'home#documente'
  get 'user77', to: 'home#user77'
  get 'evaluare_tipologie_ayurvedica', to: 'home#evaluare_tipologie_ayurvedica'

  ##get 'home/listavegetalegratis', to: 'home#listavegetalegratis', as: :listavegetalegratis_home
  get 'home/listavegetalegratis/:acces', to: 'home#listavegetalegratis', as: :listavegetalegratis_home
  
  get 'home/userip', to: 'home#userip', as: 'userip'
  get 'cazuriparticulare', to: 'home#cazuriparticulare', as: 'cazuriparticulare'


  get 'home/mergi/:mesaj', to: 'home#mergi', as: 'home_mergi'


  get 'successtripe', to: 'home#successtripe', as: 'successtripe'
  get 'home/cookiestest', to: 'home#cookiestest'
  get '/termeni-conditii', to: 'home#termeni_conditii'
  get '/politica-confidentialitate', to: 'home#politica_confidentialitate'
  get '/politica-cookies', to: 'home#politica_cookies'
  get '/politica-gdpr', to: 'home#politica_gdpr'
  get '/servicii', to: 'home#servicii'
  get '/resetareparola', to: 'home#resetareparola'
  get '/panouadmin', to: 'home#panouadmin'
  get '/tabeleahoy', to: 'home#tabeleahoy', as: 'tabeleahoy_home'

  get '/contact', to: 'home#contact'
  post '/contact', to: 'home#contact'
  get 'xlsxtopg/index'
  get 'gestionare_useri_cursuri/index'
  get '/gestionare_useri_cursuri/import_from_xlsx_cursantinutritie', to: 'gestionare_useri_cursuri#import_from_xlsx_cursantinutritie', as: 'import_from_xlsx_cursantinutritie_gestionare_useri_cursuri'
  get 'gestionare_useri_cursuri/stergecursntinutritie', to: 'gestionare_useri_cursuri#stergecursntinutritie', as: 'stergecursntinutritie_gestionare_useri_cursuri'
 
  get '/xlsxtopg/preluaredate', to: 'xlsxtopg#preluaredate', as: 'preluaredate_xlsxtopg'

app/models/comanda.rb
class Comanda < ApplicationRecord
    has_many :comenzi_prods, dependent: :destroy
    has_many :prods, through: :comenzi_prods, source: :prod
    belongs_to :user
    has_one :adresa_comenzi, class_name: 'AdresaComenzi'
    has_one :facturaproforma
  end
  

app/controllers/comandas_controller.rb
class ComandasController < ApplicationController
  before_action :set_comanda, only: %i[ show edit update destroy ]
  before_action :set_user_admin, only: %i[index edit show new destroy select_comanda_id edit_comenziprod update_comenziprod select_edit_comenziprod index11 edit11 new11]

  before_action :set_comenzi_prod1, only: [:edit11, :update11, :destroy11] #pt tabela ComenziProd1

  # GET /comandas or /comandas.json
  def index
    @comandas = Comanda.all.order(id: :desc)
  end
  
  def select_comanda_id
    # Aici, nu avem nevoie de niciun cod în special, doar să renderizăm vizualizarea
  end
  def edit_comenziprod
    @comenziprod = ComenziProd.find_by(comanda_id: params[:comanda_id])
    unless @comenziprod
      redirect_to root_path, alert: 'ComenziProd nu a fost găsit!'
    end
end

  
def update_comenziprod
  
  @comenziprod = ComenziProd.find_by(comanda_id: params[:id])
  puts("iata id-ul: #{@comenziprod.id}")
  if @comenziprod.update(comenziprod_params)
    redirect_to root_path, notice: 'ComenziProd a fost actualizat cu succes.'
  else
    render :edit
  end
  

  # restul codului...
end



  def select_edit_comenziprod
    if params[:comanda_id].present?
      redirect_to edit_comenziprod_path(comanda_id: params[:comanda_id])
    else
      # poți adăuga un flash de alertă sau altă logică
      redirect_to select_comanda_id_path, alert: "ID-ul comenzii nu este valid."
    end
  end
  


  # GET /comandas/1 or /comandas/1.json
  def show
  end

  # GET /comandas/new
  def new
    @comanda = Comanda.new
  end

  # GET /comandas/1/edit
  def edit
  end

  # POST /comandas or /comandas.json
  def create1 #aceasta metoda este fosta create  care a fost creata cu scaffold si am renuntat la ea
    @comanda = Comanda.new(comanda_params)

    respond_to do |format|
      if @comanda.save
        format.html { redirect_to comanda_url(@comanda), notice: "Comanda was successfully created." }
        format.json { render :show, status: :created, location: @comanda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comanda.errors, status: :unprocessable_entity }
      end
    end
  end

  def create #folosesc aceasta metoda pentru a adauga manual o comanda care e prin banca si NU prin Stripe
    
    user = User.find_by(email: params[:comanda][:emailcurrent])
    unless user
      redirect_to new_comanda_path, alert: 'Userul nu a fost găsit.' and return
    end
    @comanda = Comanda.new(comanda_params)
    @comanda.user_id = user.id if user
    @comanda.datacomenzii = Time.now
    @comanda.statecomanda1 = 'Initiata'
    @comanda.statecomanda2 = 'Finalizata'
    @comanda.stateplata1 = 'Achitata'
    @comanda.telefon = user.telefon
    #@comanda.plataprin = 'alta modalitate'
    @prod = Prod.find_by(id: comanda_params[:prodid]) # presupunem că Prod este numele modelului tău
    if @prod
      @comanda.stateplata3 = "acces #{@prod.valabilitatezile} zile"
      @comanda.stateplata2 = @prod.pret
      @comanda.total = @prod.pret
    else
      # dă o valoare implicită sau lasă necompletat, în caz că produsul nu există
      @comanda.stateplata3 = "negasit"
    end
    max_numar = Comanda.maximum(:numar)
    next_numar = max_numar ? max_numar + 1 : 1
  
    @comanda.numar = next_numar


   


    if @prod
    respond_to do |format|
      if @comanda.save
        # Adaugă produsul la comandă
        ComenziProd.create!(
          comanda_id: @comanda.id,
          prod_id: @comanda.prodid,
          user_id: @comanda.user_id,
          validat: 'Finalizata',
          datainceput: Time.now,
          datasfarsit: Time.now + Prod.find(@comanda.prodid).valabilitatezile.to_i.days

        )

        
        
        format.html { redirect_to comanda_url(@comanda), notice: "Comanda a fost creată cu succes." }
        format.json { render :show, status: :created, location: @comanda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comanda.errors, status: :unprocessable_entity }
      end
    end
  end
  end


  # PATCH/PUT /comandas/1 or /comandas/1.json
  def update
    respond_to do |format|
      if @comanda.update(comanda_params)
        format.html { redirect_to comanda_url(@comanda), notice: "Comanda was successfully updated." }
        format.json { render :show, status: :ok, location: @comanda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comanda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comandas/1 or /comandas/1.json
  def destroy
    @comanda.destroy

    respond_to do |format|
      format.html { redirect_to comandas_url, notice: "Comanda was successfully destroyed." }
      format.json { head :no_content }
    end
  end
####################
def index11
  @comenzi_prod1 = ComenziProd1.all.order(id: :desc)
end  
def new11  
  @comenzi_prod1 = ComenziProd1.new
end

def edit11  
  
end
def create11
  @comenzi_prod1 = ComenziProd1.new(comenziprod1_params)
  puts("ComenziProd1 este: #{@comenzi_prod1.id}")

  if @comenzi_prod1.save
    redirect_to index11_comandas_path, notice: 'Comanda produs a fost creată cu succes.'
  else
    puts @comenzi_prod1.errors.full_messages
    render :new11, status: :unprocessable_entity
  end
end


def update11
  if @comenzi_prod1.update(comenziprod1_params)
    redirect_to index11_comandas_path, notice: 'Comanda produs a fost actualizată cu succes.'
  else
    render :edit11
  end
end
def destroy11
  @comenzi_prod1.destroy
  redirect_to index11_comandas_path, notice: 'Comanda produs a fost ștearsă.'
end

####################
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comanda
      @comanda = Comanda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comanda_params
      params.require(:comanda).permit(:datacomenzii, :numar, :statecomanda1, :statecomanda2, :stateplata1, :stateplata2, :stateplata3, :user_id, :emailcurrent, :emailplata, :total, :plataprin, :prodid, :prodcod, :telefon)
    end
    

    def set_user_admin
      if !current_user
        redirect_to root_path, alert: "Nu ai permisiunea de a accesa această pagină."
        return
      end  
      unless current_user.role == 1
        redirect_to root_path, alert: "Nu ai permisiunea de a accesa această pagină."
        return
      end
    end

    def comenziprod_params
      params.require(:comenzi_prod).permit(:user_id, :prod_id, :comanda_id, :datainceput, :datasfarsit, :validat, :taxa2324, :cantitate, :pret_bucata, :pret_total, :obs)
    end
    def comenziprod1_params
      params.require(:comenzi_prod1).permit(:user_id, :prod_id, :comanda_id, :datainceput, :datasfarsit, :validat, :taxa2324, :cantitate, :pret_bucata, :pret_total, :obs)
    end
    def set_comenzi_prod1
      @comenzi_prod1 = ComenziProd1.find(params[:id])
    end

end

app/helpers/comandas_helper.rb
module ComandasHelper
end

app/views/comandas/_comanda.html.erb
<div id="<%= dom_id comanda %>">
  <p>
    <strong>Datacomenzii:</strong>
    <%= comanda.datacomenzii %>
  </p>

  <p>
    <strong>Numar:</strong>
    <%= comanda.numar %>
  </p>

  <p>
    <strong>Statecomanda1:</strong>
    <%= comanda.statecomanda1 %>
  </p>

  <p>
    <strong>Statecomanda2:</strong>
    <%= comanda.statecomanda2 %>
  </p>

  <p>
    <strong>Stateplata1:</strong>
    <%= comanda.stateplata1 %>
  </p>

  <p>
    <strong>Stateplata2:</strong>
    <%= comanda.stateplata2 %>
  </p>

  <p>
    <strong>Stateplata3:</strong>
    <%= comanda.stateplata3 %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comanda.user_id %>
  </p>

  <p>
    <strong>Emailcurrent:</strong>
    <%= comanda.emailcurrent %>
  </p>

  <p>
    <strong>Emailplata:</strong>
    <%= comanda.emailplata %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= comanda.total %>
  </p>

  <p>
    <strong>Plataprin:</strong>
    <%= comanda.plataprin %>
  </p>

  <p>
    <strong>Prodid:</strong>
    <%= comanda.prodid %>
  </p>

  <p>
    <strong>Prodcod:</strong>
    <%= comanda.prodcod %>
  </p>

  <p>
    <strong>Telefon:</strong>
    <%= comanda.telefon %>
  </p>

</div>

app/views/comandas/_form11.html.erb
<%= form.label :user_id, 'User ID' %>
<%= form.number_field :user_id %>

<%= form.label :prod_id, 'Prod ID' %>
<%= form.number_field :prod_id %>

<%= form.label :comanda_id, 'Comandă ID' %>
<%= form.number_field :comanda_id %>

<%= form.label :datainceput, 'Data Început' %>
<%= form.date_field :datainceput %>

<%= form.label :datasfarsit, 'Data Sfârșit' %>
<%= form.date_field :datasfarsit %>

<%= form.label :validat, 'Validat' %>
<%= form.text_field :validat %>

<%= form.label :taxa2324, 'Taxa 2324' %>
<%= form.number_field :taxa2324 %>

<%= form.label :cantitate, 'Cantitate' %>
<%= form.number_field :cantitate %>

<%= form.label :pret_bucata, 'Preț Bucată' %>
<%= form.number_field :pret_bucata, step: 0.01 %>

<%= form.label :pret_total, 'Preț Total' %>
<%= form.number_field :pret_total, step: 0.01 %>

app/views/comandas/edit.html.erb
<h1>Editing comanda</h1>

<%= render "form", comanda: @comanda %>

<br>

<div>
  <%= link_to "Show this comanda", @comanda %> |
  <%= link_to "Back to comandas", comandas_path %>
</div>

app/views/comandas/edit_comenziprod.html.erb
<h3>Editare ComenziProd cu ID-ul Comenzii: <%= @comenziprod.comanda_id %></h3>
<% if @comenziprod.errors.any? %>
  <ul>
    <% @comenziprod.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @comenziprod, url: update_comenziprod_path(@comenziprod.comanda_id), method: :patch do |f| %>
    <%= f.label :user_id, "Alege User" %>
  <%= f.collection_select :user_id, User.all, :id, :id %>
  

  <div class="form-group">
    <%= f.label :prod_id, "ID Produs:" %>
    <%= f.text_field :prod_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :comanda_id, "ID Comandă:" %>
    <%= f.text_field :comanda_id, class: 'form-control', readonly: true %>
  </div>

  <div class="form-group">
    <%= f.label :datainceput, "Data Început:" %>
    <%= f.date_field :datainceput, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datasfarsit, "Data Sfârșit:" %>
    <%= f.date_field :datasfarsit, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :validat, "Validat:" %>
    <%= f.text_field :validat, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :taxa2324, "Taxa 2324:" %>
    <%= f.text_field :taxa2324, class: 'form-control' %>
  </div>

  <%= f.submit "Salvează Modificările", class: 'btn btn-primary' %>

<% end %>

app/views/comandas/index.html.erb
<p style="color: green"><%= notice %></p>


  <h1 class="my-4">Comenzi</h1>
  <%= link_to 'Inapoi la Panou administrare', panouadmin_path, class: "btn btn-primary" %></br>
  <%= link_to "Comanda noua folosim doar pentru cei care au achitat prin banca pt acces viitor - pentru a fi inregistrati si ei ca au platit", new_comanda_path, class: "btn btn-success mt-3" %>
  <table class="table table-sm table-striped">
    <thead>
      <tr>
        <th scope="col">Data Comenzii</th>
        <th scope="col">Nr</th>
        <th scope="col">Status1</th>
        <th scope="col">Status2</th>
        <th scope="col">Achitat</th>
        <th scope="col">Suma</th>
        <th scope="col">Acces</th>
        <th scope="col">User</th>
        <th scope="col">Email user</th>
        <th scope="col">Email factura</th>
        <th scope="col">Email Stripe</th>
        <th scope="col">Total</th>
        <th scope="col">Plataprin</th>
        <th scope="col">Prodid</th>
        <th scope="col">Prodcod</th>
        <th scope="col">Telefon</th>
        <th scope="col">Produs</th>                
        <th scope="col">Actions</th>
        <th scope="col">Detalii factura</th>
      </tr>
    </thead>
    <tbody>
      <% @comandas.each do |comanda| %>
        <tr>
          <td style="width: 10%;"><%= comanda.datacomenzii %></td>
          <td style="width: 5%;"><%= comanda.numar %></td>
          <td style="width: 8%;"><%= comanda.statecomanda1 %></td>
          <td style="width: 8%;"><%= comanda.statecomanda2 %></td>
          <td style="width: 8%;"><%= comanda.stateplata1 %></td>
          <td style="width: 8%;"><%= comanda.stateplata2 %></td>
          <td style="width: 8%;"><%= comanda.stateplata3 %></td>
          <td style="width: 5%;"><%= comanda.user_id %></td>
          <td style="width: 5%;"><%= comanda.user.email %></td>
          <td style="width: 10%;"><%= comanda.emailcurrent %></td>
          <td style="width: 10%;"><%= comanda.emailplata %></td>
          <td style="width: 5%;"><%= comanda.total %></td>
          <td style="width: 8%;"><%= comanda.plataprin %></td>
          <td style="width: 8%;"><%= comanda.prodid %></td>
          <td style="width: 8%;"><%= comanda.prodcod %></td>
          <td style="width: 8%;"><%= comanda.telefon %></td>
          <td style="width: 10%;">
  <% comanda.prods.each do |prod| %>
    <%= prod.nume %>
  <% end %>
</td>
          <td style="width: 10%;">
            <%= link_to "Show", comanda, class: "btn btn-primary btn-sm" %>
            <%= link_to "Edit", edit_comanda_path(comanda), class: "btn btn-secondary btn-sm" %>
            <%= link_to "Delete", comanda, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>            
          </td>
          <% if comanda.user_id.present? %>
          <td>
            <%= link_to 'Detalii facturare', detaliifacturare_path(comanda.user_id), class: "btn btn-info" %>
          </td>
        <% else %>
          <td>No user associated</td>
        <% end %>
        


        </tr>
      <% end %>
    </tbody>
  </table>

app/views/comandas/new.html.erb
<h1>New comanda</h1>

<%= render "form", comanda: @comanda %>

<br>

<div>
  <%= link_to "Back to comandas", comandas_path %>
</div>

app/views/comandas/select_comanda_id.html.erb
<h3>Alege Comanda ID pentru Editare</h3>

<%= form_tag select_edit_comenziprod_path, method: :post do %>
    <%= label_tag :comanda_id, "Introdu ID-ul comenzii:" %>
    <%= text_field_tag :comanda_id %>
    <%= submit_tag "Editează" %>
<% end %>

app/views/comandas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comanda %>

<div>
  <%= link_to "Edit this comanda", edit_comanda_path(@comanda) %> |
  <%= link_to "Back to comandas", comandas_path %>

  <%= button_to "Destroy this comanda", @comanda, method: :delete %>
</div>