config/routes.rb
Rails.application.routes.draw do 
  get 'xml/animaplant_api', to: 'xml#animaplant_api'
  get 'xml/animaplant_api', to: 'xml#animaplant_api', as: :animaplant_api
  post 'xml/animaplant', to: 'xml#animaplant', as: :xml_animaplant
  post 'xml/proxy_pdf', to: 'xml#proxy_pdf'  # Schimbăm din GET în POST

  get '/animaplant_api', to: 'xml#animaplant_api'
  post '/xml_animaplant', to: 'xml#animaplant'
  post '/generate_pdf', to: 'xml#generate_pdf'

  get 'xml/animaplant', to: 'xml#animaplant'
  post 'xml/animaplant', to: 'xml#animaplant'

  get "set_language", to: "language#set"


  get '/autocomplete_tara', to: 'detaliifacturares#autocomplete_tara'
  get '/autocomplete_judet', to: 'detaliifacturares#autocomplete_judet'
  get '/autocomplete_localitate', to: 'detaliifacturares#autocomplete_localitate'
  get '/autocomplete_tara2', to: 'date_facturares#autocomplete_tara'
  get '/autocomplete_judet2', to: 'date_facturares#autocomplete_judet'
  get '/autocomplete_localitate2', to: 'date_facturares#autocomplete_localitate'




  get 'cursuri_ayurveda/ayurveda_padartha', to: 'cursuri_ayurveda#ayurveda_padartha', as: 'ayurveda_padartha'
  get 'cursuri_ayurveda/export_to_xlsx_plata_ayurveda_padartha', to: 'cursuri_ayurveda#export_to_xlsx_plata_ayurveda_padartha', as: 'export_xlsx_plata_ayurveda_padartha'
  get 'cursuri_ayurveda/download2/*linkzip', to: 'cursuri_ayurveda#download2', as: 'cursuri_ayurveda_download2', format: false
  #get 'cursuri_ayurveda/psihofonoterapie', to: 'cursuri_ayurveda#psihofonoterapie', as: 'psihofonoterapie'
  get 'psihofonoterapie', to: 'cursuri_ayurveda#psihofonoterapie', as: 'psihofonoterapie'

  get 'rasayana/general', to: 'rasayana#general', as: 'rasayana_general'
  get 'rasayana/modul1', to: 'rasayana#modul1', as: 'rasayana_modul1'
  get 'rasayana/modul2', to: 'rasayana#modul2', as: 'rasayana_modul2'
  
  get 'rasayana/seminarii', to: 'rasayana#seminarii_rasayana', as: 'rasayana_seminarii'


  post 'home/make_unlisted', to: 'home#make_unlisted'
  get 'get_encryption_key', to: 'home#get_encryption_key'
  get 'priority_flag', to: 'application#priority_flag'  ##este  metoda get_encryption_key sub alta denumire
  get 'proxy_video', to: 'home#proxy_video'
  get '/generate_session_token', to: 'application#generate_session_token'
  
  
  resources :localitatis do
    collection do
      post 'import_judete'
      post 'import_tari'
      post 'import_localitati'
    end
  end
  get 'tabere/export_to_xlsx', to: 'tabere#export_to_xlsx_plata_tayv24', as: 'export_tayv24_xlsx'
  get 'tabere/export_to_xlsx_plata_tayt24', to: 'tabere#export_to_xlsx_plata_tayt24'
  get 'tabere/tayv24', to: 'tabere#tayv24', as: 'tayv24'
  get 'tabere/tayt24', to: 'tabere#tayt24', as: 'tayt24'
  get 'facturas/raport_accesare_facturi', to: 'facturas#raport_accesare_facturi', as: 'raport_accesare_facturi'
 
  get 'facturaproformas/facturi_xml_ayusgrup', to: 'facturaproformas#facturi_xml_ayusgrup', as: 'facturi_xml_ayusgrup'
  get 'facturaproformas/:id/download_xml_ayusgrup', to: 'facturaproformas#download_xml_ayusgrup', as: 'download_xml_ayusgrup'
  get 'facturaproformas/facturi_xml_lunar', to: 'facturaproformas#facturi_xml_lunar', as: 'facturi_xml_lunar'


  get 'facturaproformas/:id/download_cbc_xml_ayusgrup', to: 'facturaproformas#download_cbc_xml_ayusgrup', as: 'download_cbc_xml_ayusgrup'
  get 'facturaproformas/facturi_xml_lunar_cbc', to: 'facturaproformas#facturi_xml_lunar_cbc', as: 'facturi_xml_lunar_cbc'
  get 'facturaproformas/facturi_cbc_lunar', to: 'facturaproformas#facturi_cbc_lunar', as: 'facturi_cbc_lunar' 
  get 'facturaproformas/facturi_xml_lunar_romania', to: 'facturaproformas#facturi_xml_lunar_romania', as: 'facturi_xml_lunar_romania'
  get 'facturaproformas/facturi_non_romania_clients', to: 'facturaproformas#facturi_non_romania_clients', as: 'facturi_non_romania_clients'
  get 'facturaproformas/facturi_xml_lunar_non_romania', to: 'facturaproformas#facturi_xml_lunar_non_romania', as: 'facturi_xml_lunar_non_romania'
  #get 'download_xml_zip_ayusgrup', to: 'facturaproformas#download_xml_zip_ayusgrup'
  get '/download_xml_zip_ayusgrup', to: 'facturaproformas#download_xml_zip_ayusgrup', as: 'download_xml_zip_ayusgrup'
  resources :facturaproformas do
    collection do
      get :generare_facturi
      post :creareproforma
      get 'facturaproformas/not_in_users', to: 'facturaproformas#not_in_users', as: 'not_in_users_facturaproformas'
      get :not_in_users, to: 'facturaproformas#not_in_users', as: 'not_in_users'
      get :situatii_lunare
      get :analiza_lunara
      get :download_analiza_lunara
      
    end
  
    member do
      get :download1, to: 'facturaproformas#download1', as: 'download1'
      get :download, to: 'facturaproformas#download', as: 'download'
      post :create_stripe_session
    end
  end
  
  
  
  
  
  get 'cancelstripe', to: 'home#cancelstripe', as: 'cancelstripe'
  

  resources :firmeproformas
  resources :an32324s do
    collection do
      get 'preluarean3'
    end
  end

  resources :firmas
  

  resources :date_facturares
  get 'export_datefacturare', to: 'date_facturares#export_datefacturare', as: :export_datefacturare
  
 # Rute personalizate care au prioritate
 get 'tvs/canal1', to: 'tvs#canal1'
 get 'tvs/canal2', to: 'tvs#canal2'
 get 'tvs/canal3', to: 'tvs#canal3'
 get 'tvs/rasayana1', to: 'tvs#rasayana1' #rasayana1
 get 'tvs/ayurveda_padartha', to: 'tvs#ayurveda_padartha' #ayurveda_padartha
 get 'tvs/reprogramare_curs', to: 'tvs#reprogramare_curs' #reprogramari video-uri -Thalia
 get 'tvs/seminarii', to: 'tvs#seminarii'

  

 get 'tvs/listacanal1', to: 'tvs#listacanal1', as: 'listacanal1'
 get 'tvs/listacanal2', to: 'tvs#listacanal2', as: 'listacanal2'
 get 'tvs/listacanal3', to: 'tvs#listacanal3', as: 'listacanal3'

 ### Rutele CRUD standard pentru tvs, inclusiv show
 
 resources :tvs
resources :listacanal2s
patch 'listacanal2s/:id', to: 'listacanal2s#update', as: :update_listacanal2
resources :listacanal3s
patch 'listacanal3s/:id', to: 'listacanal3s#update', as: :update_listacanal3

 

  get '/show_cerere_voluntar/:id', to: 'contractes#show_cerere_voluntar', as: 'show_cerere_voluntar'
  get '/show_gdpr_voluntar/:id', to: 'contractes#show_gdpr_voluntar', as: 'show_gdpr_voluntar'
  get '/show_contract_voluntar/:id', to: 'contractes#show_contract_voluntar', as: 'show_contract_voluntar'
  get '/show_fisa_postului_voluntar/:id', to: 'contractes#show_fisa_postului_voluntar', as: 'show_fisa_postului_voluntar'
  get 'test_wasabi_access', to: 'home#test_wasabi_access'
  get 'home/test_debian', to: 'home#test_debian'


  get 'test_ssl_connection', to: 'home#test_ssl_connection'
  get 'get_new_presigned_url', to: 'home#get_new_presigned_url'
  get 'get_presigned_url', to: 'home#get_presigned_url'
  get 'generate_presigned_key_url', to: 'home#generate_presigned_key_url'

  get 'home/test', to: 'home#test'
  get 'show_ip', to: 'home#show_ip'


  post '/newsletter', to: 'home#newsletter'
  get 'home/lista_newsletter', to: 'home#lista_newsletter', as: 'lista_newsletter'

  get 'admin/users/export', to: 'admin#export_users_to_xlsx', as: 'export_admin_users'
  get 'home/newsletters/export', to: 'home#export_newsletter_subscribers', as: 'export_newsletter_subscribers'



  get 'vajikarana/modul1', to: 'vajikarana#modul1', as: 'vajikarana_modul1'
  get 'vajikarana/modul2', to: 'vajikarana#modul2', as: 'vajikarana_modul2'
  #get 'vajikarana/download/:linkzip', to: 'vajikarana#download', as: 'vajikarana_download'
  get 'vajikarana/download/*linkzip', to: 'vajikarana#download', as: 'vajikarana_download', format: false
  get 'vajikarana/download2/*linkzip', to: 'vajikarana#download2', as: 'vajikarana_download2', format: false  

  get 'traditia_ayurvedica/amnaya', to: 'traditia_ayurvedica#amnaya', as: 'amnaya'
  get 'traditia_ayurvedica/jivaka', to: 'traditia_ayurvedica#jivaka', as: 'jivaka'
  get 'traditia_ayurvedica/asita', to: 'traditia_ayurvedica#asita', as: 'asita'
  get 'traditia_ayurvedica/jamadagni', to: 'traditia_ayurvedica#jamadagni', as: 'jamadagni'
  get 'traditia_ayurvedica/hiranyaksha', to: 'traditia_ayurvedica#hiranyaksha', as: 'hiranyaksha'
  get 'traditia_ayurvedica/sharaloma', to: 'traditia_ayurvedica#sharaloma', as: 'sharaloma'
  get 'traditia_ayurvedica/saunaka', to: 'traditia_ayurvedica#saunaka', as: 'saunaka'
  get 'traditia_ayurvedica/maudgalya', to: 'traditia_ayurvedica#maudgalya', as: 'maudgalya'
  get 'traditia_ayurvedica/cognitronica', to: 'traditia_ayurvedica#cognitronica', as: 'cognitronica'
  get 'traditia_ayurvedica/nimi', to: 'traditia_ayurvedica#nimi' , as: 'nimi'
  get 'traditia_ayurvedica/shukracharya', to: 'traditia_ayurvedica#shukracharya' , as: 'shukracharya'
  get 'traditia_ayurvedica/modele_spirituale', to: 'traditia_ayurvedica#modele_spirituale'


  #get 'traditia_ayurvedica/performanta_cognitiva', to: 'traditia_ayurvedica#performanta_cognitiva', as: 'performanta_cognitiva'
  # Definirea rutei cu un nume personalizat pentru helper-ul de cale
  get 'traditia_ayurvedica/optimizarea_performantelor_cognitive', to: 'traditia_ayurvedica#performanta_cognitiva', as: 'optimizarea_performantelor_cognitive'

  # ...alte rute...
  get 'nutritie4/index'
  get 'nutritie4/export_to_xlsx', to: 'nutritie4#export_to_xlsx_plata_nutritie4', as: 'export_nutritie4_xlsx'
  
  get 'nutritie5', to: 'nutritie5#index'
  get 'nutritie5/export_to_xlsx', to: 'nutritie5#export_to_xlsx_plata_nutritie5', as: 'export_nutritie5_xlsx'
  get 'contract/contract_voluntar', to: 'contractes#semneaza_contract', as: 'contract_voluntar'
  get 'contract/contract_voluntar1', to: 'contractes#semneaza_contract1', as: 'contract_voluntar1'

  post '/contractes', to: 'contractes#create', as: 'contractes_create' # Aici, 'contractes_create' este numele rutei
  #get 'contractes/vizualizeaza/:id', to: 'contractes#vizualizeaza_contract', as: 'contracte_vizualizeaza'
  get 'contractes/:id/vizualizeaza', to: 'contractes#vizualizeaza_contract', as: 'vizualizeaza_contract_contracte'

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/copyright.html.erb
<style>
#nutritie1 .cm h2 {
    font-size:22px;
}
#nutritie1 .register{
    border: 1px solid #4b0082;
    background-color:#4b0082;
}
#nutritie1 .cm h3{
    font-size:18px;
    font-weight:800;
    margin-bottom:0;
}
#nutritie1 .register{
    margin:0;
    margin-top:20px;
}
#nutritie1 .table td {
    text-align:center;
}
@media screen and (max-width: 720px) {
    #nutritie1 .register{
        margin:0 auto;
        margin-top:20px;
    }
    .cm{
        text-align:center;
    }
}

</style>
<% content_for :title, "Ayush Cell Romania: Copyright" %>
<% content_for :meta_tags do %>
  <meta name="description" content="Descoperiți importanța adaptării (satmya) alimentației la tipologia constituțională ayurvedică proprie (dosha) și impactul acesteia asupra sănătății.">
  <meta name="keywords" content="ayurveda, nutritie ayurvedica, dosha, vata, pitta, kapha, dosha-prakriti, greutatea ideala, formule greutate ideala">
  <link rel="canonical" href="https://www.ayushcell.ro/Copyright">
<% end %>

<div class="container" id="nutritie1">
<%= render 'layouts/sideleft' %>

<div class="cr" style="background-color: white; ">
    <h1 class="first-tittle">Ayush Cell Romania: Copyright</h1>
    <h2 class="main-title">Declarație de Copyright</h2>

<p>Toate articolele, prezentările și materialele audio-video de pe site-ul ayushcell.ro, inclusiv, dar fără a se limita la documente, cursuri scrise, prezentări PowerPoint, înregistrări video, fișiere PDF și alte resurse disponibile, sunt protejate prin drepturi de autor.</p>

<p style="margin-bottom:-10px;"><strong>Utilizare Permisă</strong></p>
<p>Toate materialele menționate anterior, inclusiv cele cu drept de vizualizare pe site sau de descărcare, sunt destinate exclusiv utilizării în scopuri personale de învățare.<br><br>

Orice altă utilizare a materialelor, inclusiv, dar fără a se limita la distribuirea, reproducerea, modificarea, publicarea sau utilizarea acestora în scopuri comerciale, vânzarea, împrumutul, închirierea, relicențierea, sublicențierea, transmiterea sau redistribuirea, este strict interzisă fără obținerea prealabilă a acordului scris din partea titularilor drepturilor de autor.<br>

Este interzisă copierea, înregistrarea (prin orice mijloace, inclusiv capturi de ecran sau software de înregistrare audio-video) sau distribuirea în orice formă a prezentărilor, materialelor text sau fișierelor audio-video disponibile pe site-ul ayushcell.ro, fără obținerea prealabilă a permisiunii scrise explicite din partea Ayush Cell Romania SRL sau a titularilor drepturilor de autor asupra acestor materiale.</p>

<p style="margin-bottom:-10px;"><strong>Contact</strong></p>
<p style="margin-bottom:0px;">Pentru cereri referitoare la permisiuni sau alte întrebări legate de drepturile de autor, vă rugăm să ne contactați la:</p>
<p>Ayush Cell Romania SRL<br>
Str. Ostasilor nr. 15, sector 1, București, România<br>
Tel.: 0749 079 619<br>
Email: <a href="mailto:ayushcellromania@gmail.com">ayushcellromania@gmail.com</a></p>

<p style="margin-bottom:-10px;"><strong>Notificare Legală</strong></p>
<p>Orice încălcare a acestei declarații de copyright poate conduce la acțiuni legale, incluzând cereri de despăgubiri și alte măsuri legale necesare pentru protejarea drepturilor de autor.</p>




<section>

</section>

</div></div>

app/views/home/listavegetalegratis.html.erb
<h1 class="text-center mb-4" style="color: green;"><%=@mesaj1%></h1>
<h1 class="text-center mb-4" style="color: green;"><%=@mesaj2%></h1>
<section class="c1">
<div class="d-flex justify-content-center mt-5">
  <%= link_to 'Intră în aplicație', lista_vegetales_path, class: "btncontact btn btn-lg btn-primary", style: "font-size: 24px; padding: 20px 40px;" %>
</div>
</br></br></br></br></br></br>
</section>

app/views/home/recuperare_cursuri.html.erb
<h1 style="text-align: center;">Recuperare cursuri</h1></br>

<div id="videos">
  <table class="table">
    <thead>
    <tr>
        
        <th>Nume</th>
        <th>Descriere</th>       
        <th>Actiune</th>
        
    </tr>
    </thead>
    <tbody>
    <% @myvideo.each do |video| %>
        <tr><td><%= video.nume %></td>
        <td><%= video.descriere %></td>
        <td><%= link_to "Vezi video", myvideo144_path(id: video.id, link: video.link), class: "btn btn-primary" %></td>
      </tr><% end %>
    </tbody>
  </table>
</div>

app/views/home/resetareparola.html.erb
<h1 style="max-width: 1280px; margin: 0 auto; text-align: center; font-size: 1.5em; padding: 50px 10px;">
   
Un link pentru resetarea parolei a fost trimis catre adresa dumneavoastra de email</h1>

app/views/home/servicii.html.erb
<section class="tabel-container rotate-landscape">

    <h1 class="alimente-nutritionale" id="ListaIngredienteVegetale">Consultare Selectiva Lista Ingrediente Vegetale</h1>

    <%if !current_user ||  (current_user && !@prods.empty?) %>



    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead class="thead-dark">
                <tr class= "desk">
                    <th style="height: 40px; vertical-align:middle; width: 30%;">Servicii</th>                    
                    <th style="height: 40px; vertical-align:middle; width: 30%;">Detalii</th>
                    
                    <th style="height: 40px; vertical-align:middle; width: 14%;">Pret</th>
                    <th style="height: 40px; vertical-align:middle; width: 12%;">Actiune</th>
                </tr>      
            </thead>
            <tbody>
            <% @prods.each do |prod| %>
                    <tr>
                    
                    <td><%= prod.nume %></td> 
                                          
                        <td><%= prod.detalii %></td> 
                        
                         <td style="text-align:center;"><%= prod.pret.to_i %> lei</td>
                         <% if current_user %>
                         <td style="text-align:center;">
                           <%= link_to 'Comanda', datefacturare_path(s: prod.id), class: 'btn btn-primary' %>
                         </td>
                       <% else %>
                         <td style="text-align:center;">
                           <%= link_to 'Accesează', new_user_session_with_return_path('lg'), class: 'btn btn-primary' %>
                         </td>
                       <% end %>
                       
                        </tr>  
                <% end %>  
            </tbody>
        </table>
    </div>
<%end%>    

    
</section>


<script type="text/javascript">
        console.log("Test simplificat de consolă.");
    </script>

app/views/home/sesiune_vara.html.erb
<style>
#vacanta .cm h2 {
    font-size:22px;
}
#vacanta .register{
    border: 1px solid #4b0082;
    background-color:#4b0082;
}
#vacanta .cm h3{
    font-size:18px;
    font-weight:800;
    margin-bottom:0;
}
#vacanta .register{
    margin:0;
    margin-top:20px;
}
#vacanta .table td {
    text-align:center;
}
@media screen and (max-width: 720px) {
    #vacanta .register{
        margin:0 auto;
        margin-top:20px;
    }
    .cm{
        text-align:center;
    }
    .cm h3{
        margin-top:20px;
    }
}

</style>
<% content_for :title, "Ayush Cell Romania: Sesiunea de vara" %>
<% content_for :meta_tags do %>
<meta name="description" content="Participă la seminariile interactive de vacanță organizate de Ayush Cell Romania.">
<meta name="keywords" content="ayurveda, seminarii de vacanță, sănătate holistică, cursuri online, dosha, vata, pitta, kapha, ayush cell romania">

  <link rel="canonical" href="https://www.ayushcell.ro/sesiune_vara">
<% end %>

<div class="container" id="vacanta">
<%= render 'layouts/sideleft' %>

<div class="cr" style="background-color: white; ">
    <h1 class="first-tittle">Ayush Cell Romania: Seminarii Interactive de Vacanță</h1>
    <h2 class="main-title" >Seminarii interactive de ayurveda pentru perioada vacanței de vara</h2>
   <section>
        <div class="row1 center" style="max-width:920px; margin:0 auto;">
            <div class="r1c1" style="height: 350px;">
                <img src="<%= image_url('vacanta.webp') %>" alt="Seminarii Ayurveda">
            </div>
            <div class="r1c2">
                <p>Vă invităm să participați la seminariile interactive de vacanță dedicate cursurilor de Ayurveda pentru grupele 1, 2 și 3. Aceste seminarii au ca scop oferirea unei înțelegeri profunde a principiilor și practicilor Ayurveda, permițând explorarea diferitelor aspecte ale acestei științe milenare.  </p>
                
                <% if !current_user %>      
                <div class="r1c2">
                    <%= link_to 'Înscrie-te acum', new_user_session_with_return_path('sesiune_vara'), class: 'register' %>
                </div>
                <%elsif current_user && !@has_access%>
                <%= link_to 'Înscrie-te acum', '#VideoNutritie', class: 'register' %>
                <% end %> 
            </div>
        </div>
    </section>
    <section class="cm">
        

                <h3>Descriere:</h3>
                <p>Aceste seminarii reprezintă o oportunitate excepțională pentru aprofundarea cunoștințelor în Ayurveda. Participanții vor beneficia de interacțiuni directe cu lectori specializați în Ayurveda, având posibilitatea de a adresa întrebări în timp real și de a primi răspunsuri avizate. Aceste seminarii au ca scop oferirea unei înțelegeri profunde a principiilor și practicilor Ayurveda, permițând explorarea diferitelor aspecte ale acestei științe milenare. Prin intermediul acestor sesiuni interactive, cunoștințele de Ayurveda pot fi extinse semnificativ, pot fi clarificate diferite concepte complexe sau pot fi identificate modalități practice de aplicare a noțiunilor deja învățate în viața de zi cu zi</p>
                <h3>Seminariile sunt opționale se desfășoară în zilele de:</h3>
                <ul style="text-align:left;">
                    <li>1 august 2024</li>
                    <li>8 august 2024</li>
                    <li>15 august 2024</li>
                    <li>22 august 2024</li>
                    <li>29 august 2024</li>
                </ul>
                <p><strong>Interval orar:</strong> 18:00 - 20:00</p>
                <h3>Înscriere:</h3>
                <p>Pentru a vă înscrie, vă rugăm să achiziționați accesul la seminarii. Pentru detalii suplimentare, vă invităm să ne contactați direct pe pagina <a href="https://ayushcell.ro/contact" target="_blank">ayushcell.ro/contact</a>. Sesiunile se vor desfășura LIVE pe platforma Zoom. Linkul de acces Zoom va fi afișat in pagină după efectuarea plății.</p>
                <h3>Acces digital:</h3>
                <p>Vizionarea înregistrărilor poate fi realizată în această pagină timp de 60 de zile de la achiziționarea acestei opțiuni.</p>
                <p>Vă așteptăm cu drag!</p>
    </section>



    <h3 class="alimente-nutritionale" id="VideoNutritie" style="font-size:28px;">Acces prezentari pe platforma ZOOM si digital</h3>
<% if !current_user || (current_user && !@has_access) || (current_user && current_user.role == 1) %>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead class="thead-dark">
                <tr class= "desk">
                    <th style="height: 40px; vertical-align:middle; width: 30%;">Servicii</th>                    
                    <th style="height: 40px; vertical-align:middle; width: 30%;">Detalii</th>
                    
                    <th style="height: 40px; vertical-align:middle; width: 14%;">Pret</th>
                    <th style="height: 40px; vertical-align:middle; width: 12%;">Actiune</th>
                </tr>      
            </thead>
            <tbody>
            <% @prods.each do |prod| %>
              <tr>
                  <td><%= prod.nume %></td>                   
                  <td><%= prod.detalii %></td>
                  <td><%= prod.pret.to_i %> lei</td>
                  <% if current_user %>
                       <td style="text-align:center;">
                         <%= link_to 'Acceseaza', datefacturare_path(s: prod.id), class: 'btn btn-primary' %>
                       </td>
                     <% else %>
                       <td style="text-align:center;">
                         <%= link_to 'Acceseaza', new_user_session_with_return_path('sesiune_vara'), class: 'btn btn-primary' %>
                       </td>
                     <% end %>
                  
            </tr>
              <% end %>  
                </tbody>
              </table>
          </div>
<% end %>
<% if current_user && (@has_access || current_user.role == 1) %>
<section class="cm">
        <h3 style="color: rgb(7 6 187);font-size:18px;">Link participare ZOOM</h3>
        <p style="margin-top: -5px;"><a href="https://us02web.zoom.us/j/82301072867?pwd=uXaNNqhZQ6rO9BvAgsbJTQ2EGb2sX9.1">https://us02web.zoom.us/j/82301072867?pwd=uXaNNqhZQ6rO9BvAgsbJTQ2EGb2sX9.1</a></p>
        <p style="margin-top: -20px;">Meeting ID: 853 4505 9664</p>
        <p style="margin-top: -20px;">Passcode: 438696</p> </br></br>

        <h2 style= "text-align: center;padding: 0 10px; font-size:28px;">Acces prezentari video sesiuni interactive August 2024</h2></br>



<div id="videos">
  <table class="table">
    <thead>
    <tr>
        <th>Nr</th>
        <th>Nume</th>
        <th>Descriere</th>       
        <th>Actiune</th>
        
    </tr>
    </thead>
    <tbody>
    <% @myvideo.each do |video| %>
        <%= render partial: 'video1', locals: { video: video } %>
      <% end %>
    </tbody>
  </table>
</div>



    </section>
<% end %>  

 </div>
 </div>

app/views/home/tabeleahoy.html.erb
<h2>Ultimele 30 de vizite</h2>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>User ID</th>
      <th>Nume</th>
      <th>User Agent</th>
      <th>Landing Page</th>
      <th>Browser</th>
      <th>OS</th>
      <th>Device Type</th>
      <th>Started At</th>
    </tr>
  </thead>
  <tbody>
    <% @ahoy_visits.each do |visit| %>
      <tr>
        <td><%= visit.user_id %></td>
        <td><%= visit.user&.name %></td> <!-- Presupunand ca numele este un atribut al modelului User -->
        <td><%= visit.user_agent %></td>
        <td><%= visit.landing_page %></td>
        <td><%= visit.browser %></td>
        <td><%= visit.os %></td>
        <td><%= visit.device_type %></td>
        <td><%= visit.started_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Ultimele 70 de evenimente</h2>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Id</th>  
      <th>User ID</th>
      <th>Nume</th>
      <th>Name</th>
      <th>Properties</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <% @ahoy_events.each do |event| %>
      <tr>
      <td><%= event.id %></td>
        <td><%= event.user_id %></td>
        <td><%= event.user&.name %></td>
        <td><%= event.name %></td>
        <td><%= event.properties %></td>
        <td><%= event.time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/userip.html.erb
<h1>User IPs</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th>ID</th>
      <th>User ID</th>
      <th>Adresa Ip</th>
      <th>Curs Promo</th>
      <th>Creat</th>
      
      <th>Email User</th>
      <th>Nume User</th>
    </tr>
  </thead>

  <tbody>
    <% @userip.each do |userip| %>
      <tr>
        <td><%= userip.id %></td>
        <td><%= userip.user_id %></td>
        <td><%= userip.ip_address %></td>
        <td><%= userip.curspromo %></td>
        <td><%= userip.created_at %></td>
        
        <td><%= userip.user&.email %></td> 
        <td><%= userip.user&.name %></td> 
      </tr>
    <% end %>
  </tbody>
</table>